// Syncs client-safe keys from the project-root `.env` into
// `assets/config/local.env` so debug/device runs can load Supabase config
// without relying on --dart-define flags.
//
// Run manually:  dart run tool/sync_local_env.dart
// Also invoked automatically before Android builds (see build.gradle.kts).

import 'dart:io';

/// Keys safe to bundle for client-side Supabase/OAuth (public or anon).
const _clientSafeKeys = {
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
  'SUPABASE_REDIRECT_URL',
  'SUPABASE_EMAIL_REDIRECT_URL',
  'SUPABASE_GOOGLE_CALLBACK',
  'GOOGLE_WEB_CLIENT_ID',
  'GOOGLE_ANDROID_CLIENT_ID',
  'GOOGLE_IOS_CLIENT_ID',
  'CLOUD_NAME',
};

void main() {
  final root = Directory.current;
  final source = File('${root.path}/.env');
  final targetDir = Directory('${root.path}/assets/config');
  final target = File('${targetDir.path}/local.env');

  if (!source.existsSync()) {
    stderr.writeln(
      '[sync_local_env] No .env at project root.\n'
      '  Copy .env.example → .env and fill in your Supabase values.',
    );
    if (!target.existsSync()) {
      exit(1);
    }
    stderr.writeln('[sync_local_env] Keeping existing assets/config/local.env');
    exit(0);
  }

  targetDir.createSync(recursive: true);

  final out = StringBuffer('# Generated by tool/sync_local_env.dart — do not edit.\n');
  var copied = 0;

  for (final line in source.readAsLinesSync()) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
    final eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    final key = trimmed.substring(0, eq).trim();
    if (!_clientSafeKeys.contains(key)) continue;
    final value = trimmed.substring(eq + 1).trim();
    if (value.isEmpty) continue;
    out.writeln('$key=$value');
    copied++;
  }

  if (copied == 0) {
    stderr.writeln(
      '[sync_local_env] .env has no SUPABASE_URL / SUPABASE_ANON_KEY entries.',
    );
    exit(1);
  }

  target.writeAsStringSync(out.toString());
  stdout.writeln(
    '[sync_local_env] Wrote $copied key(s) to assets/config/local.env',
  );
}
